### PR TITLE
fix(woff2): /assets/inter-latin.4fe6132f.woff2  is 404

### PR DESCRIPTION
**Pull request by xiejun-net**
image

### CODE REVIEW

**Review by Jinjiang — APPROVED** [review]

**Comment by Jinjiang** [comment]
@brc-dd I checked this file doesn't exist anymore in `dist/assets`. So I'd approve and merge it. However, if you think any other assets need to be prefetched manually. Feel free to fire an issue or a PR. Thanks.

**Comment by brc-dd** [comment]
@Jinjiang It's appearing on my networks tab:

image

**Comment by Jinjiang** [comment]
Understood. Then I think the PR could be directly on vuejs/docs instead. WDYT?

**Comment by brc-dd** [comment]
But the translations are also using this theme, right?

**Comment by Jinjiang** [comment]
The translations, at least the zh-cn one, would be synced with the code and config from the docs repo. So no worries about that. And since it's a docs-specific thing, it's also better to keep the knowledge close/together.

**Comment by brc-dd** [comment]
Ah, cool then. Let me know once you release a new version here. I'll update the docs.

**Comment by brc-dd** [comment]
Ah, Evan added this at vitepress level (https://github.com/vuejs/vitepress/commit/24735dbcde15be41bc2697a4ea44001a1a583511) 🎉

**Pull request merged**
