### PR TITLE
feat: adding VTCodeGroup component to the @vue/theme (#46)

### LINKED ISSUE #46: Code Group Component
I need a VTCodeGroup for the docs -- I rolled my own, but it's coupled to what I'm putting inside of it. We should have one that matches the theme and is generic.

https://github.com/vuejs/docs/pull/1493#issuecomment-1037925511

### PR DESCRIPTION
**Pull request by JessicaSachs**
Resolves #46 

Adds a VTCodeGroup component to replace https://github.com/vuejs/docs/blob/main/src/guide/scaling-up/TestingApiSwitcher.vue

Also @kiaking it fixes the mobile responsive issues you saw with the original implementation. To test it, I replaced the custom component I pasted above locally. I was looking for a way to demo/test out the component in this repo. Is there any infra for that?

https://user-images.githubusercontent.com/2801156/155276939-631c87b0-94c8-4038-afd8-f52d8662cd3b.mov

### CODE REVIEW

**Comment by JessicaSachs** [comment]
BTW (just curious)... why aren't we using scoped slots in this repo?

**Comment by kiaking** [comment]
Wonderful work! 🙌 

> I was looking for a way to demo/test out the component in this repo. Is there any infra for that?

I think `demo` folder is used for this purpose 👍 

> BTW (just curious)... why aren't we using scoped slots in this repo?

Well we do in `vitepress` folder. The reason we use external css in `core` is that because at the beginning of this repo, we thought it might be nice to be able to use `core` component or styles without using Vue component.

Like when we have pure HTML only stuff, we can reuse the same css. However, later on, we decided this repo to be Vue website exclusive, I'm thinking to put those css into component with scoped css 😅  And also merge `core` folder and `vitepress` folder.

**Comment by JessicaSachs** [comment]
> I think demo folder is used for this purpose 👍
Yeah I had issues with the demo folder because it doesn't pull in all of the code block styles, so when I went to test this, the CodeGroup component didn't look great. Nbd though.

Thx for the explanation about the css. I was so confused about why we wouldn't use scoped styles. Thought there must've been a reason 😂

LMK if you need anything else 🎉

**Comment by yyx990803** [comment]
New theme has been published and updated in vuejs/docs so feel free to open a PR there to refactor the usage :)

**Pull request merged**
