### PR TITLE
fix: search style

### PR DESCRIPTION
**Pull request by zhousg**
# Problem
image
hover
image

### CODE REVIEW

**Comment by Jinjiang** [comment]
May I know how to reproduce that problem, and the environment as much as possible, please?

**Comment by zhousg** [comment]
> May I know how to reproduce that problem, and the environment as much as possible, please?

This is what happens when you open the search pop-up window. Macos  Chrome

**Comment by zhousg** [comment]
image
image
image

**Comment by zhousg** [comment]
Macos 12.3.1    Chrome   106.0.5249.119

**Comment by chaichai-fe** [comment]
me too! 
image

**Comment by Jinjiang** [comment]
@chaichai-fe @zhousg really thanks for the reproductions. Would you mind me bothering you one more time to check?

Is that still reproducible via an existing Netlify online preview like here?
https://deploy-preview-77--vue-vitepress-theme.netlify.app/ (#77)

And this time it would be also appreciated if you can try it on a private browsing mode.

THanks. 🙏

**Comment by zhousg** [comment]
image


> 

There's still a problem

**Pull request merged**
