### PR TITLE
fix(icon): updated twitter icon

### PR DESCRIPTION
**Pull request by stevenks17**
Not sure if I should clean up and remove or replace Twitter icon references with just IconX  or keep as is with just having twitter associated with IconX for now.

### CODE REVIEW

**Comment by kiaking** [comment]
Yeah I say it is about time now to make the switch. @Jinjiang What would you say 👀

**Comment by Jinjiang** [comment]
@stevenks17 there is already an x option in L27. To trigger it, just write `{ icon: 'x', link: 'https://x.com/vuejs' },` in config. See more #99. So I don't think we need this PR. :-)

**Comment by Jinjiang** [comment]
For the docs issue, I think what we need is to release a new version of this theme and update it to the docs.
/cc @yyx990803

**Comment by stevenks17** [comment]
@Jinjiang  will that also work for the about page as changing it in the social links didnt update twitter icons in the about page  IIRC

**Pull request merged**
